[package]
name = "cuda"
version = "0.1.0"
edition = "2024"

[dependencies]

[profile.release]
split-debuginfo = "packed"
debug = true
debug-assertions = false
overflow-checks = false
panic = 'abort'
strip = false
#Performance stuff
codegen-units = 1
opt-level = 3
lto = "fat"